apiVersion: v1
kind: Secret
metadata:
  name: waste-env
  namespace: waste-app
type: Opaque
stringData:
  # -------- MariaDB (caso o serviço algum dia precise) --------
  DB_HOST: "mariadb"
  DB_PORT: "3306"
  DB_USER: "waste_user"
  DB_PASS: "wastepass"
  DB_NAME: "waste_db"

  # -------- Kafka --------
  KAFKA_SERVER: "kafka.waste-app.svc.cluster.local:9092"
  KAFKA_TOPICS: "bin_monitoring,nfc_logs,nfc-tags"

  # -------- Redis --------
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

  # -------- Flask WebSocket --------
  FLASK_PORT: "5006"
  FLASK_HOST: "0.0.0.0"
  FLASK_DEBUG: "true"

  # -------- Uvicorn (FastAPI, se necessário) --------
  UVICORN_HOST: "0.0.0.0"
  UVICORN_PORT: "5008"
