apiVersion: v1
kind: Service
metadata:
  name: kafka-ws-bridge
  namespace: waste-app
spec:
  selector:
    app: kafka-ws-bridge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5006
  type: ClusterIP
