version: "3.9"

services:
  kong:
    image: kong:3.5
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
    volumes:
      - ./kong/kong.yml:/kong/kong.yml