apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-init
  namespace: waste-app
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS waste_db;
    USE waste_db;

    CREATE TABLE bins (
      id INT AUTO_INCREMENT PRIMARY KEY,
      sensor_serial VARCHAR(100) NOT NULL,
      lat DOUBLE NOT NULL,
      lon DOUBLE NOT NULL,
      nfc_token VARCHAR(100) NOT NULL,
      topic VARCHAR(100) NOT NULL,
      fill_level VARCHAR(10);
    );

    CREATE TABLE users (
      id INT AUTO_INCREMENT PRIMARY KEY,
      uid VARCHAR(255) UNIQUE NOT NULL,
      role ENUM('admin', 'user') NOT NULL,
      imei VARCHAR(50),
      usage_count INT DEFAULT 0,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
