apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: waste-app
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
