apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: waste-app
data:
  kong.yaml: |
    _format_version: "3.0"

    services:
      - name: s_backend
        url: http://api:80
        routes:
          - name: s_backend_route
            paths:
              - /api

      - name: s_routes
        url: http://routesapi-service:80
        routes:
          - name: s_routes_route
            paths:
              - /routes
            plugins:
              - name: cors
                config:
                  origins:
                    - "*"
                  methods:
                    - GET
                    - POST
                    - DELETE
                    - PUT
                  headers:
                    - "*"
                  credentials: true

      - name: s_monitoring
        url: http://bin-monitoring:80
        routes:
          - name: s_monitoring_route
            paths:
              - /monitoring
            strip_path: true
            plugins:
              - name: cors
                config:
                  origins:
                    - "*"
                  methods:
                    - GET
                    - POST
                    - PUT
                    - DELETE
                  headers:
                    - "*"
                  credentials: true

      - name: kafka_ws
        url: http://kafka-ws-bridge:80
        routes:
          - name: kafka_ws_route
            paths:
              - /socket.io
            protocols:
              - http
            strip_path: false
            preserve_host: true
