apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: waste-app
data:
  kong.yaml: |
    _format_version: "3.0"

    services:
      - name: s_backend
        url: http://api:80
        routes:
          - name: s_backend_route
            paths:
              - /api

      - name: s_routes
        url: http://routesapi-service:80
        routes:
          - name: s_routes_route
            paths:
              - /v2/routes         
            strip_path: false      
            plugins:
              - name: cors
                config:
                  origins:
                    - "*"
                  methods:
                    - GET
                    - POST
                    - DELETE
                    - PUT
                  headers:
                    - "*"
                  credentials: true

      - name: s_monitoring
        url: http://bin-monitoring:80
        routes:
          - name: s_monitoring_route
            paths:
              - /v2/binmonitoring
            strip_path: false
            plugins:
              - name: cors
                config:
                  origins:
                    - "*"
                  methods:
                    - GET
                    - POST
                    - PUT
                    - DELETE
                  headers:
                    - "*"
                  credentials: true

      - name: kafka_ws
        url: http://kafka-ws-bridge:80
        routes:
          - name: kafka-ws-route
            paths:
              - /ws
            protocols:
              - http
              - https
            strip_path: false
            preserve_host: true
            plugins:
              - name: cors
                config:
                  origins:
                    - "*"               
                  methods:
                    - GET
                    - POST
                    - OPTIONS
                  headers:
                    - "*"               
                  credentials: true

            
      - name: posting_service
        url: http://posting-service:80
        routes:
          - name: posting_service_route
            paths:
              - /v1/posting
            strip_path: false
            plugins:
              - name: cors
                config:
                  origins:
                    - "*"
                  methods:
                    - POST
                  headers:
                    - "*"
                  credentials: true
      
      - name: flutter_web
        url: http://flutter-web-svc:5200
        routes:
          - name: flutter_web_route
            paths:
              - /
            strip_path: false
            plugins:
              - name: cors
                config:
                  origins:
                    - "*"
                  methods:
                    - GET
                  headers:
                    - "*"
                  credentials: true