apiVersion: v1
kind: Secret
metadata:
  name: waste-env
  namespace: waste-app
type: Opaque
stringData:
  DB_HOST: "mariadb"
  DB_PORT: "3306"
  DB_USER: "waste_user"
  DB_PASS: "wastepass"
  DB_NAME: "waste_db"

  KAFKA_SERVER: "kafka:9092"
  KAFKA_TOPICS: "bin_monitoring,nfc_logs,nfc-tags"

  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

  FLASK_PORT: "5006"
  FLASK_HOST: "0.0.0.0"
  FLASK_DEBUG: "true"

  UVICORN_HOST: "0.0.0.0"
  UVICORN_PORT: "5008"
