CREATE TABLE bins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sensor_serial VARCHAR(100) NOT NULL,
  lat DOUBLE NOT NULL,
  lon DOUBLE NOT NULL,
  nfc_token VARCHAR(100) NOT NULL,
  topic VARCHAR(100) NOT NULL
);
