apiVersion: v1
kind: ConfigMap
metadata:
  name: binmonitoring-config
  namespace: waste-app
data:
  FLASK_PORT: "5004"
  FLASK_HOST: "0.0.0.0"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  KAFKA_SERVER: kafka.waste-app.svc.cluster.local:9092
  KAFKA_TOPIC: iot_logs
  LOOKUP_FILE: /data/sensor_lookup.txt
  FLASK_DEBUG: "False"
