apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: waste-app
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - name: kafka-internal
      port: 9092
      targetPort: 9092
    - name: kafka-external
      port: 29092
      targetPort: 29092
      nodePort: 30092  # Porta externa para sensores
