apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: waste-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:3.6
          ports:
            - containerPort: 9092  # Listener interno
            - containerPort: 29092  # Listener externo
          env:
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: zookeeper:2181

            # Dois listeners: um interno, um externo
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://:9092,EXTERNAL://:29092

            # Anunciar endereços corretamente
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka.waste-app.svc.cluster.local:9092,EXTERNAL://193.136.82.35:30092

            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT

            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
