apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: waste-app
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
      nodePort: 30092 # ou outro entre 30000–32767
